# Site settings
url: https://lufevida.github.io
baseurl: /html5up-hyperspace
copyright: Untitled
title: Hyperspace
tagline: by HTML5 UP
description: "Just another fine responsive site template designed by <a href="http://html5up.net">HTML5 UP</a><br />and released for free under the <a href="http://html5up.net/license">Creative Commons</a>."
contactTagline: Phasellus convallis elit id ullamcorper pulvinar. Duis aliquam turpis mauris, eu ultricies erat malesuada quis. Aliquam dapibus, lacus eget hendrerit bibendum, urna est aliquam sem, sit amet imperdiet est velit quis lorem.

# Contact
address: "12345 Somewhere Road #654<br />Nashville, TN 00000-0000<br />USA"
email: name@provider.com
phone: (012) 345-6789
twitter: username
facebook: username
github: username
instagram: username
linkedin: username

# Featurette -- leave values blank if you do not want them to appear
featuretteTitle: What we do
featuretteTagline: Phasellus convallis elit id ullamcorper pulvinar. Duis aliquam turpis mauris, eu ultricies erat malesuada quis. Aliquam dapibus, lacus eget hendrerit bibendum, urna est aliquam sem, sit amet imperdiet est velit quis lorem.
featuretteLink: elements.html
feature1Title: Lorem ipsum amet
feature1Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature1Icon: icon major fa-code
feature2Title: Aliquam sed nullam
feature2Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature2Icon: icon major fa-lock
feature3Title: Sed erat ullam corper
feature3Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature3Icon: icon major fa-cog
feature4Title: Veroeros quis lorem
feature4Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature4Icon: icon major fa-desktop
feature5Title: Urna quis bibendum
feature5Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature5Icon: icon major fa-chain
feature6Title: Aliquam urna dapibus
feature6Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature6Icon: icon major fa-diamond